alias cddocs="cd /media/mauro/Users/Mauro/Dropbox\ \(Personal\)/PERSONAL/DOCUMENTACION"
alias cddrop="cd /media/mauro/Users/Mauro/Dropbox\ \(Personal\)"
alias dockerrun="~/bin/dockerrun"    
alias gbv="git branch -vv"
alias mwin="sudo mount /dev/nvme0n1p3 /media/mauro"
