ln -sv ~/git/dotfiles/addins.json  ~/.config/rstudio/keybindings/addins.json -f
ln -sv ~/git/dotfiles/aliases.zsh ~/.oh-my-zsh/custom/aliases.zsh -f
ln -sv ~/git/dotfiles/editor_bindings.json  ~/.config/rstudio/keybindings/editor_bindings.json -f
ln -sv ~/git/dotfiles/gitconfig ~/.gitconfig -f
ln -sv ~/git/dotfiles/gitignore ~/.gitignore -f
ln -sv ~/git/dotfiles/markdown.snippets  ~/.config/rstudio/snippets/markdown.snippets -f
ln -sv ~/git/dotfiles/pam_environment ~/.pam_environment -f
ln -sv ~/git/dotfiles/profile ~/.profile -f
ln -sv ~/git/dotfiles/Rprofile ~/.Rprofile -f
ln -sv ~/git/dotfiles/r.snippets  ~/.config/rstudio/snippets/r.snippets -f
ln -sv ~/git/dotfiles/rstudio_bindings.json  ~/.config/rstudio/keybindings/rstudio_bindings.json -f
ln -sv ~/git/dotfiles/rstudio-prefs.json ~/.config/rstudio/rstudio-prefs.json -f
ln -sv ~/git/dotfiles/vimrc ~/.vimrc -f
ln -sv ~/git/dotfiles/zshrc ~/.zshrc -f
