ln -svf ~/git/dotfiles/addins.json  ~/.config/rstudio/keybindings/addins.json
ln -svf ~/git/dotfiles/aliases.zsh ~/.oh-my-zsh/custom/aliases.zsh 
ln -svf ~/git/dotfiles/editor_bindings.json  ~/.config/rstudio/keybindings/editor_bindings.json 
ln -svf ~/git/dotfiles/gitconfig ~/.gitconfig 
ln -svf ~/git/dotfiles/gitignore ~/.gitignore
ln -svf ~/git/dotfiles/markdown.snippets  ~/.config/rstudio/snippets/markdown.snippets
ln -svf ~/git/dotfiles/pam_environment ~/.pam_environment 
ln -svf ~/git/dotfiles/profile ~/.profile 
ln -svf ~/git/dotfiles/Rprofile ~/.Rprofile
ln -svf ~/git/dotfiles/r.snippets  ~/.config/rstudio/snippets/r.snippets 
ln -svf ~/git/dotfiles/rstudio_bindings.json  ~/.config/rstudio/keybindings/rstudio_bindings.json 
ln -svf ~/git/dotfiles/rstudio-prefs.json ~/.config/rstudio/rstudio-prefs.json 
ln -svf ~/git/dotfiles/vimrc ~/.vimrc 
ln -svf ~/git/dotfiles/zshrc ~/.zshrc
